### ISSUE TITLE
Prompt being killed

### ISSUE THREAD

**Issue by jbodah** [brigade/overcommit#228]
Was trying to have a "soft" hook that runs YARD stats and prompts the user if they want to still continue with the commit:

Current quick and dirty YARD stats hook:

```rb
module Overcommit::Hook::PreCommit
  class EnsureYardCoverage < Base
    def run
      applicable_files.select! { |f| f[/(app|lib|test\/concerns|test\/lib)/] }
      return :pass if applicable_files.empty?
      report_coverage
      abort? ? :fail : :pass
    end

    private

    def report_coverage
      system('yard stats --list-undoc ' << applicable_files.join(' '))
    end

    def abort?
      print "\nWould you like to continue with your commit? (y/n): "
      res = $stdin.gets.chomp
      res == 'n' || res == 'N'
    end
  end
end
```

And the issue I'm having:

```sh
Running pre-commit hooks
Checking for YARD coverage.......................[EnsureYardCoverage] Files:           1Modules:         1 (    1 undocumented)
Classes:         0 (    0 undocumented)
Constants:       5 (    5 undocumented)
Methods:         4 (    4 undocumented)
 0.00% documented

Undocumented Objects:

(in file: /Users/Bodah/repos/backupify/backupify/lib/marketo_record.rb)
MarketoRecord
MarketoRecord::CHANGED_GAPPS_USERS_IDS_KEY
MarketoRecord::CHANGED_SFDC_USERS_IDS_KEY
MarketoRecord::NEW_MARKETO_USERS_COOKIES_KEY
MarketoRecord::USER_ATTRIBUTES
MarketoRecord::MARKETO_TIMEZONE
MarketoRecord.save_data_for_update
MarketoRecord#sfdc_updating_hash
MarketoRecord#gapps_updating_hash
MarketoRecord#storage_usage_for_user

Would you like to continue with your commit? (y/n): FAILED
Hook raised unexpected error
undefined method `chomp' for nil:NilClass
/Users/Bodah/repos/backupify/backupify/.git-hooks/pre_commit/ensure_yard_coverage.rb:18:in `abort?'
/Users/Bodah/repos/backupify/backupify/.git-hooks/pre_commit/ensure_yard_coverage.rb:7:in `run'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/utils.rb:170:in `with_environment'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:106:in `run_hook'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:58:in `each'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:58:in `run_hooks'
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:39:in `run'
.git/hooks/pre-commit:54:in `<main>'
```

Originally I figured it was this code, but I forked and removed `::isolate_from_interrupts` and it didn't seem to do anything:

```rb
module Overcommit
  class HookRunner
    #...

    # Loads and runs the hooks registered for this {HookRunner}.
    def run
      # ASSUMPTION: we assume the setup and cleanup calls will never need to be
      # interrupted, i.e. they will finish quickly. Should further evidence
      # suggest this assumption does not hold, we will have to separately wrap
      # these calls to allow some sort of "are you sure?" double-interrupt
      # functionality, but until that's deemed necessary let's keep it simple.
      InterruptHandler.isolate_from_interrupts do
        @context.setup_environment
        load_hooks
        result = run_hooks
        @context.cleanup_environment
        result
      end
    end

    #...
  end
end
```

Any thoughts?

**Comment by sds** [comment]
Hey @jbodah,

The fundamental issue here is that git hooks are not intended to be interactive, since you could execute them from scripts which are not associated with a TTY console (which is why your code is failing in this case, since `$stdin` is closed at this point. 

We too made this mistake but then fixed this in 7957fa47f0267d9fa399d0004941e1d2ec80386.

I would encourage you to rethink the design of your hooks to not require interactivity. The future work we have planned for Overcommit will introduce parallelized hook runs (see #144), which will make any sort of user input impractical.
