### ISSUE TITLE
Commit message hooks fail on very large commit messages with possibly weird characters

### ISSUE THREAD

**Issue by lencioni** [brigade/overcommit#244]
I was recently using `git commit --verbose` (which includes the diff of what is to be committed), and wanted to commit a change that removed many many lines of code. After committing, my commit failed because of the commit message hooks:

```
Running commit-msg hooks
Checking subject capitalization..................[CapitalizedSubject] FAILED
Hook raised unexpected error
invalid byte sequence in UTF-8
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_context/commit_msg.rb:22:in `block in commit_message_lines'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_context/commit_msg.rb:22:in `reject'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_context/commit_msg.rb:22:in `commit_message_lines'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_context/commit_msg.rb:10:in `commit_message'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_context/commit_msg.rb:5:in `empty_message?'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook/commit_msg/capitalized_subject.rb:5:in `run'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/utils.rb:170:in `with_environment'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:106:in `run_hook'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:58:in `each'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:58:in `run_hooks'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:39:in `block in run'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
/Users/joe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:24:in `run'
.git/hooks/commit-msg:54:in `<main>'
```

The same thing happened for the EmptyMessage hook. I'm not entirely sure if the problem was because the commit message may have contained some weird characters, or if it was just because they were too large. In any case, it might solve this problem and make things faster if if the lines that git ignores were thrown away before the commit message hooks run.

**Comment by sds** [comment]
Fixed by 96e83bb.
