### ISSUE TITLE
RuboCop hook and error formatting

### ISSUE THREAD

**Issue by deivid-rodriguez** [brigade/overcommit#270]
When I reviewed the default configuration to customize my own I removed the default `--format=emacs` flag, because I thought "I like RuboCop's default output". But doing this breaks the hook

```
Analyzing with RuboCop......................................[RuboCop] FAILED
Hook raised unexpected error
Unexpected output: unable to determine line number or type of error/warning for message 'Inspecting 50 files'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook/pre_commit/base.rb:31:in `block in extract_messages'
org/jruby/RubyArray.java:2300:in `map'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook/pre_commit/base.rb:28:in `extract_messages'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook/pre_commit/rubo_cop.rb:14:in `run'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/utils.rb:211:in `with_environment'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook_runner.rb:106:in `run_hook'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
org/jruby/RubyArray.java:1560:in `each'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook_runner.rb:58:in `run_hooks'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook_runner.rb:39:in `block in run'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/hook_runner.rb:24:in `run'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/cli.rb:195:in `run_all'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/lib/overcommit/cli.rb:27:in `run'
/home/davidr/.gem/jruby/2.2.2/gems/overcommit-0.27.0/bin/overcommit:8:in `<top>'
org/jruby/RubyKernel.java:958:in `load'
bin/overcommit:1:in `<top>'
```

Not a big deal, but given that the hook relies on that flag being enabled, maybe it should be applied programmatically instead of from configuration, so users won't expect to be able to configure this.

Thanks!

**Comment by sds** [comment]
Hey @deivid-rodriguez,

The reason we define it in the configuration file is so if RuboCop changes the name of the formatter in a version (which they _have_ done in the past--the flag used to be `--emacs`, not `--format=emacs`), you don't need to wait on a pull request and version release of Overcommit in order to get things working again&mdash;you just update the `flags` option for the `RuboCop` hook.

Hope that explains the rationality here.

**Comment by deivid-rodriguez** [comment]
I see, thanks!
