### ISSUE TITLE
ScssLint pre-commit hook should handle commits only containing excluded files

### ISSUE THREAD

**Issue by thecristen** [brigade/overcommit#287]
My `.scss-lint.yml` is configured to exclude `file.scss`. When I try to make a commit that only involves a change in `file.scss`, the pre-commit hook errors out.

The output, with paths edited for brevity:
```
Analyzing with scss-lint...................................[ScssLint] FAILED
Hook raised unexpected error
Unexpected output: unable to determine line number or type of error/warning for message 'All files matched by the patterns [.../file.scss] were excluded by the patterns: [.../file.scss]'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook/pre_commit/base.rb:30:in `block in extract_messages'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook/pre_commit/base.rb:28:in `map'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook/pre_commit/base.rb:28:in `extract_messages'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook/pre_commit/scss_lint.rb:21:in `run'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/utils.rb:223:in `with_environment'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:106:in `run_hook'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:58:in `each'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:58:in `run_hooks'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:39:in `block in run'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
.../.rvm/gems/ruby-2.0.0-p576/gems/overcommit-0.28.0/lib/overcommit/hook_runner.rb:24:in `run'
.git/hooks/pre-commit:71:in `<main>'
```

Possibly related to #163.

**Comment by sds** [comment]
Which version of `scss-lint` are you using, @thecristen?

**Comment by thecristen** [comment]
The latest (0.38.0) as far as I know.

**Comment by sds** [comment]
The latest is 0.42.2. The gem name was changed from [`scss-lint` to `scss_lint`](https://github.com/brigade/scss-lint/releases/tag/v0.38.0) to match [Rubygems naming conventions](http://guides.rubygems.org/name-your-gem/).

**Comment by lencioni** [comment]
Perhaps we should release 0.38.1 of scss-lint that prints a warning explaining how to upgrade?

**Comment by sds** [comment]
`scss-lint 0.38.0` prints a warning when you install it:

```
⨠ gem install scss-lint
WARNING: `scss-lint` has been renamed to `scss_lint` to follow proper RubyGems naming conventions. Update your Gemfile or relevant install scripts to install `scss_lint`.
Successfully installed scss-lint-0.38.0
1 gem installed
```

**Comment by lencioni** [comment]
This seems to be coming up a fair amount though, which makes me think we need to print the warning when you run it.

**Comment by ssayer** [comment]
You may also want to change the text in the overcommit README since that still says scss-lint

**Comment by thecristen** [comment]
Also the text that comes up here:

```
14:42 $ overcommit --run
Running pre-commit hooks
Analyzing with ESLint........................................[EsLint] OK
Analyzing with RuboCop......................................[RuboCop] OK
Analyzing with scss-lint...................................[ScssLint] FAILED
'scss-lint' is not installed (or is not in your PATH)
Install it by running: gem install scss-lint
Checking Travis CI configuration.........................[TravisLint] OK
```

**Comment by thecristen** [comment]
Thanks @sds for pointing out the updated gem, hopefully I'll see it referenced in the above messaging soon.
