### ISSUE TITLE
Overcommit scss-lint hook raises error if stylesheet doesn't pass SingleLinePerSelector rule?

### ISSUE THREAD

**Issue by gsmendoza** [brigade/overcommit#306]
We encountered the following bug while committing some SCSS files. Can you confirm if it's valid?

Given the following gem versions

* overcommit 0.29.1
* scss_lint 0.38.0

And the following SCSS file:

```scss
td,
th {
    display: table-cell
}

td,
th {
    padding: 0;
}
```

And my project has the SCSS lint Overcommit hook enabled
When I try to commit the file
Then I should expect the Overcommit to report the SCSS lint issues of the file
But instead I get the following error:

```
Analyzing with scss-lint...................................[ScssLint] FAILED
Hook raised unexpected error
Unexpected output: unable to determine line number or type of error/warning for message 'th` with rule on line 1'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook/pre_commit/base.rb:30:in `block in extract_messages'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook/pre_commit/base.rb:28:in `map'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook/pre_commit/base.rb:28:in `extract_messages'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook/pre_commit/scss_lint.rb:21:in `run'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/utils.rb:170:in `with_environment'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:106:in `run_hook'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:58:in `each'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:58:in `run_hooks'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:39:in `block in run'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
/home/gsmendoza/.rvm/gems/ruby-2.2.3/gems/overcommit-0.26.0/lib/overcommit/hook_runner.rb:24:in `run'
.git/hooks/pre-commit:54:in `<main>'
```

Here's the debug output of the error:

[debug.txt](https://github.com/brigade/overcommit/files/50386/debug.txt)

**Comment by sds** [comment]
Hey @gsmendoza,

This looks like a bug with the output `scss-lint` lint is returning, which is causing Overcommit to fail since it can't parse the lint messages.

What is the output of scss-lint when you run it directly against that file? (also, you should probably update `scss-lint`, the latest version at time of writing is 0.43.2).

**Comment by trotzig** [comment]
Note that 0.38.0 was the last version of `scss-lint`, before the rename to `scss_lint`. See https://rubygems.org/gems/scss-lint/versions/0.38.0

**Comment by gsmendoza** [comment]
@sds Thanks for pointing me in the right direction. SCSS-Lint 0.43 fixes the issue.

Here's the report of scss-lint 0.38:

```
test.css.scss:3 [E] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
test.css.scss:3 [E] TrailingSemicolon: Declaration should be terminated by a semicolon
test.css.scss:6 [E] MergeableSelector: Merge rule `td,
th` with rule on line 1
test.css.scss:8 [E] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
```

And here's the report of 0.43:

```
test.css.scss:3 [E] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
test.css.scss:3 [E] TrailingSemicolon: Declaration should be terminated by a semicolon
test.css.scss:6 [E] MergeableSelector: Merge rule `td, th` with rule on line 1
test.css.scss:8 [E] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
```

With scss-lint 0.43, overcommit doesn't raise an error:

```
Analyzing with scss-lint...................................[ScssLint] FAILED
Errors on modified lines:
/home/gsmendoza/projects/love-with-food/Love-With-Food/test.css.scss:3 [E] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
/home/gsmendoza/projects/love-with-food/Love-With-Food/test.css.scss:3 [E] TrailingSemicolon: Declaration should be terminated by a semicolon
/home/gsmendoza/projects/love-with-food/Love-With-Food/test.css.scss:6 [E] MergeableSelector: Merge rule `td, th` with rule on line 1
/home/gsmendoza/projects/love-with-food/Love-With-Food/test.css.scss:8 [E] Indentation: Line should be indented 2 spaces, but was indented 4 spaces
```
