### ISSUE TITLE
Unhelpful error message when RuboCop is not installed

### ISSUE THREAD

**Issue by lencioni** [brigade/overcommit#335]
I am using rbenv and I had RuboCop installed in different version of Ruby but not the version I happened to be using. When trying to commit, I got this output:

```
Analyzing with RuboCop......................................[RuboCop] FAILED
Hook raised unexpected error
Unexpected output: unable to determine line number or type of error/warning for message ''
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook/pre_commit/base.rb:31:in `block in extract_messages'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook/pre_commit/base.rb:28:in `map'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook/pre_commit/base.rb:28:in `extract_messages'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook/pre_commit/rubo_cop.rb:19:in `run'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/utils.rb:259:in `with_environment'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook_runner.rb:152:in `run_hook'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook_runner.rb:88:in `block in consume'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook_runner.rb:85:in `loop'
/Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/overcommit-0.32.0.rc1/lib/overcommit/hook_runner.rb:85:in `consume'
```

Running `rubocop` alone gave me this output:

```
rbenv: rubocop: command not found

The `rubocop' command exists in these Ruby versions:
  2.0.0-p481
  2.3.0
```

After installing rubocop, it seemed to work better (I got a different error but this one was more actionable).

**Comment by sds** [comment]
This situation is difficult to address. The core problem is that `rbenv` installs a shim for `rubocop` the first time you install. However, this shim exists in your path even if you switch to a version of Ruby that does not have that gem installed yet. Thus you'll get the error you so saying "The `rubocop' command exists in these Ruby versions:". Since this doesn't match the message format the hook is expecting, it fails.

The intention of showing a stack trace in this case is because we wanted hook authors to get feedback on whether or not their hook message regex was correct. However, I think it would be reasonable for us to swallow the stack trace and instead display all of STDOUT/STDERR in this case. That way in your situation you would have seen (as an example):

```
Analyzing with RuboCop......................................[RuboCop] FAILED
Hook raised unexpected error
Unexpected output: unable to determine line number or type of error/warning for message:
rbenv: rubocop: command not found

The `rubocop' command exists in these Ruby versions:
  2.0.0-p481
  2.3.0
```

**Comment by lencioni** [comment]
Agreed, that would be much better!
