### ISSUE TITLE
specify npm script to run for the EsLint hook

### ISSUE THREAD

**Issue by deepak** [brigade/overcommit#338]
configured the EsLint hook like

```
  EsLint:
    enabled: true
    command: './node_modules/eslint/bin/eslint.js'
    include: '**/*.js'
```

which works

but ideally would prefer to specify the npm script command 

example:

in node's package.json

```
"scripts": {
    "lint": "eslint ."
  },
"devDependencies": {
    "eslint": "^2.0.0-rc.1",
    "eslint-plugin-react": "^3.16.1"
  }
```

and can run `npm run lint`

so want the hook config to be something like

```
  EsLint:
    enabled: true
    command: 'npm run lint'
```

is that possible ?

**Comment by sds** [comment]
Did you try it? :stuck_out_tongue:

**Comment by deepak** [comment]
thanks @sds. your tip for `command: ['npm', 'run', 'lint']` worked :-)

i had tried by suggestion about `command: 'npm run lint'`
got the error `No such file or directory - npm run lint`

full stacktrace is:

```
Running pre-commit hooks
Analyzing with ESLint........................................[EsLint] FAILED
Hook raised unexpected error
No such file or directory - npm run lint
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/unix/fork_exec_process.rb:58:in `launch_process'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:82:in `start'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/subprocess.rb:35:in `spawn'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/command_splitter.rb:66:in `block in execute'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/command_splitter.rb:65:in `map'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/command_splitter.rb:65:in `execute'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/utils.rb:184:in `execute'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook/base.rb:100:in `execute'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook/pre_commit/es_lint.rb:7:in `run'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/utils.rb:223:in `with_environment'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:107:in `block in run_hook'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/interrupt_handler.rb:63:in `disable_until_finished_or_interrupted'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:106:in `run_hook'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:59:in `block in run_hooks'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:58:in `each'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:58:in `run_hooks'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:39:in `block in run'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/hook_runner.rb:24:in `run'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/cli.rb:203:in `run_all'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/lib/overcommit/cli.rb:28:in `run'
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.31.0/bin/overcommit:7:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.3.0/bin/overcommit:23:in `load'
/usr/local/opt/rbenv/versions/2.3.0/bin/overcommit:23:in `<main>'
```

**Comment by liyaodong** [comment]
**command: `npm run lint` not working**

```yml
  EsLint:
    enabled: true
    required_executable: 'npm'
    command: ['npm', 'run', 'lint']
```
It will display `✓ All pre-commit hooks passed`

but actually run `npm run lint`, will show errors. `✖ 4 problems (4 errors, 0 warnings)`

same source code, and tracked by git.

Change to this will be work:
```yml
  EsLint:
    enabled: true
    required_executable: './node_modules/.bin/eslint'
    command: ['./node_modules/.bin/eslint']
```

**Comment by jawshooah** [comment]
Just a hunch: try `command: ['npm', 'run', 'lint', '--']`.

**Comment by liyaodong** [comment]
@jawshooah It works ! But what's that meaning ? `--`

You save my life, thanks !

**Comment by jawshooah** [comment]
You can [pass arguments to your script](https://docs.npmjs.com/cli/run-script) by adding `--` after `npm run <script-name>`. In this case, Overcommit appends [flags](https://github.com/brigade/overcommit/blob/cefbadc/config/default.yml#L222) to the `eslint` command, but since you changed the command to `npm run lint` they weren't being properly passed to `eslint`.

**Comment by liyaodong** [comment]
@jawshooah got it, real commnd will be 
`npm run lint -- --format=compact` => `eslint --format=compact`

because eslint [default config](https://github.com/brigade/overcommit/blob/master/config%2Fdefault.yml#L222) will pass this glags.

Thank again!
