### ISSUE TITLE
JavaCheckstyle - Hook raised unexpected error

### ISSUE THREAD

**Issue by gautamjain** [brigade/overcommit#358]
I'm trying to use Overcommit and JavaCheckstyle for my Android Studio project.

When running `checkstyle` from the cmd line, it catches an error correctly:

```console
» checkstyle -c checkstyle_config.xml app/src/main/java
Starting audit...
[ERROR] /Users/gj/AndroidStudioProjects/TestApp/app/src/main/java/example/com/testapp/MainActivity.java:8: 'METHOD_DEF' has more than 1 empty lines after. [EmptyLineSeparator]
Audit done.
Checkstyle ends with 1 errors.
```

However, when running `overcommit -r`, I get an unexpected error - *No such file or directory @ rb_sysopen*, even though it does exist:

```console
» overcommit -r
Running pre-commit hooks
Analyze with checkstyle..............................[JavaCheckstyle] FAILED
Hook raised unexpected error
No such file or directory @ rb_sysopen - [ERROR] /Users/gj/AndroidStudioProjects/TestApp/app/src/main/java/example/com/testapp/MainActivity.java
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `foreach'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `each'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `count'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `count_lines'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:20:in `modified_lines_in_file'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:145:in `message_on_modified_line?'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `block in handle_modified_lines'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `each'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `partition'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `handle_modified_lines'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:39:in `hook_result'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook/base.rb:260:in `process_hook_return_value'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook/base.rb:46:in `run_and_transform'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:152:in `run_hook'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:88:in `block in consume'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:85:in `loop'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:85:in `consume'

✗ One or more pre-commit hooks failed
```

### Config
```yml
PreCommit:
  JavaCheckstyle:
    enabled: true
    requires_files: true
    required_executable: 'checkstyle'
    flags: ['-c', 'checkstyle_config.xml']
    problem_on_unmodified_line: warn
```

### Sample project
[Here.  You'll probably need to `brew install checkstyle`.
](https://github.com/gautamjain/TestApp)
### Version
Overcommit 0.32.0
Ruby 2.3.0
Checkstyle 6.16.1

### Full log 
with `OVERCOMMIT_DEBUG=true`
```console
» OVERCOMMIT_DEBUG=true overcommit -r
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "6f4be9fca758be8bfcefe38731e3b3ea71b50af78c4ad747691cdde227c84739\n"
STDERR: ""
git config --local --get overcommit.configuration.signature
EXIT STATUS: 0
STDOUT: "6f4be9fca758be8bfcefe38731e3b3ea71b50af78c4ad747691cdde227c84739\n"
STDERR: ""
Running pre-commit hooks
git config --get user.name
git config --get user.email
grep -IHn ^<<<<<<<[ 	] ... (29 splittable args)
git rev-parse HEAD
EXIT STATUS: 0
checkstyle -c checkstyle_config.xml ... (1 splittable args)STDOUT: "Gautam Jain\n"

STDERR: ""
EXIT STATUS: 0
STDOUT: "xxxxxxx@gmail.com\n"
STDERR: ""
EXIT STATUS: 0
STDOUT: "72a2183bd677f4dbb31cec022ab1e0ef316df5de\n"
STDERR: ""
EXIT STATUS: 1
STDOUT: ""
STDERR: ""
EXIT STATUS: 1
STDOUT: "Starting audit...\n[ERROR] /Users/gj/AndroidStudioProjects/TestApp/app/src/main/java/example/com/testapp/MainActivity.java:8: 'METHOD_DEF' has more than 1 empty lines after. [EmptyLineSeparator]\nAudit done.\nCheckstyle ends with 1 errors.\n"
STDERR: ""
Analyze with checkstyle..............................[JavaCheckstyle] FAILED
Hook raised unexpected error
No such file or directory @ rb_sysopen - [ERROR] /Users/gj/AndroidStudioProjects/TestApp/app/src/main/java/example/com/testapp/MainActivity.java
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `foreach'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `each'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `count'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:43:in `count_lines'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_context/run_all.rb:20:in `modified_lines_in_file'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:145:in `message_on_modified_line?'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `block in handle_modified_lines'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `each'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `partition'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:57:in `handle_modified_lines'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/message_processor.rb:39:in `hook_result'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook/base.rb:260:in `process_hook_return_value'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook/base.rb:46:in `run_and_transform'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:152:in `run_hook'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:88:in `block in consume'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:85:in `loop'
/Users/gj/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/overcommit-0.32.0/lib/overcommit/hook_runner.rb:85:in `consume'

✗ One or more pre-commit hooks failed
```

**Comment by gautamjain** [comment]
@sds thanks for looking into this.

I'm actually still getting the same error after updating Overcommit in my Gemfile:

```
gem 'overcommit', git: 'https://github.com/brigade/overcommit', ref: 'be1d6a9'
```

**Comment by sds** [comment]
@gautamjain Unless you're running with `bundle exec`, your `Gemfile` won't be respected, so you'll still be running the latest gem release version of Overcommit.

**Comment by gautamjain** [comment]
Actually, I'm sorry.  It is working.  I just wasn't prefixing the command with `bundle exec`.

**Comment by gautamjain** [comment]
@sds, one more thing.  Checkstyle output may be prefixed with `[ERROR]`, `[WARN]`, or `[INFO]` depending on how your rules/checks are configured.

Is there a way those tags could be respected in the message processing regex?  I.e. Overcommit would only block when an `[ERROR]` is output.

It would be ideal if a Checkstyle [WARN] could be converted to an Overcommit warning, but maybe that would be an enhancement.

**Comment by sds** [comment]
Hey @gautamjain,

This is totally possible. I don't use the `Checkstyle` hook myself, so I'm curious how the hook should treat `INFO`-level messages. Should they simply be ignored, or are they still typically something a user would need to see?

**Comment by gautamjain** [comment]
Hi @sds,

I haven't come across any checks with their severity set to `INFO`.  Might be used rarely.

The `Checkstyle` hook could probably ignore `INFO` messages.  That way if someone wants output from  a 'Checkstyle check' to be displayed:
- by Checkstyle (in their IDE, cmd line, etc.) **and** by Overcommit - they set severity to `WARN`
- by Checkstyle only - they set severity to `INFO`

At least that leaves some extra configurability for the user.  What do you think?

**Comment by gautamjain** [comment]
Hi @sds,  any chance this would still be possible?

**Comment by sds** [comment]
Hey @gautamjain,

Would love to accept a pull request for this. You should be able to modify the regex (https://github.com/brigade/overcommit/blob/1d35fe56980327289586c89e4b6e7502c8e3a9d0/lib/overcommit/hook/pre_commit/java_checkstyle.rb#L6) to capture the error type, and then define a function to categorize based on the string (e.g. like the `HamlLint` pre-commit hook: https://github.com/brigade/overcommit/blob/1d35fe56980327289586c89e4b6e7502c8e3a9d0/lib/overcommit/hook/pre_commit/haml_lint.rb#L6-L8).
