### ISSUE TITLE
uncommenting example config generates warnings on  overcommit --run/--sign

### ISSUE THREAD

**Issue by matkoniecz** [brigade/overcommit#393]
Default .overcommit.yml contains

```
# Uncomment the following lines to make the configuration take effect.

#PreCommit:
#  RuboCop:
#    enabled: true
#    on_warn: fail # Treat all warnings as failures
#
#  TrailingWhitespace:
#    exclude:
#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes

```

Uncommenting this example config, and running `overcommit --run` (and `overcommit --sign`) results in

```
mateusz@ugluk:~/Desktop/CartoCSSHelper$ overcommit --run
PreCommit::TrailingWhitespace hook does not explicitly set `enabled` option in .overcommit.yml

/home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/lib/overcommit/configuration_loader.rb:81:in `verify_signatures': Unable to load configuration from '/home/mateusz/Desktop/CartoCSSHelper/.overcommit.yml': No previously recorded signature for configuration file. (Overcommit::Exceptions::ConfigurationError)
Run `overcommit --sign` if you trust the hooks in this repository.
	from /home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/lib/overcommit/configuration_loader.rb:67:in `load_file'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/lib/overcommit/configuration_loader.rb:55:in `load_repo_config'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/lib/overcommit/cli.rb:215:in `config'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/lib/overcommit/cli.rb:197:in `run_all'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/lib/overcommit/cli.rb:28:in `run'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overcommit-0.34.1/bin/overcommit:45:in `<top (required)>'
	from /home/mateusz/.gem/ruby/2.3.0/bin/overcommit:23:in `load'
	from /home/mateusz/.gem/ruby/2.3.0/bin/overcommit:23:in `<main>'
mateusz@ugluk:~/Desktop/CartoCSSHelper$ overcommit --sign
Updating signature for configuration file...
PreCommit::TrailingWhitespace hook does not explicitly set `enabled` option in .overcommit.yml

mateusz@ugluk:~/Desktop/CartoCSSHelper$ 
```

**Comment by sds** [comment]
Thanks for the report!
