### ISSUE TITLE
No subject in commit not expected

### ISSUE THREAD

**Issue by distorhead** [brigade/overcommit#432]
```ruby
$ git commit
Running pre-commit hooks
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 1.0.11, ~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Run BuildizerVerify.................................[BuildizerVerify] OK
Run BuildizerCiVerify.............................[BuildizerCiVerify] OK

✓ All pre-commit hooks passed

Running commit-msg hooks
Check for trailing periods in subject................[TrailingPeriod] OK
Check text width..........................................[TextWidth] OK
Check subject line................................[SingleLineSubject] OK
Check subject capitalization.....................[CapitalizedSubject] FAILED
Hook raised unexpected error
undefined method `[]' for nil:NilClass
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook/commit_msg/capitalized_subject.rb:8:in `run'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/utils.rb:260:in `with_environment'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook_runner.rb:152:in `run_hook'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook_runner.rb:88:in `block in consume'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook_runner.rb:85:in `loop'
/usr/local/rvm/gems/ruby-2.1.0/gems/overcommit-0.36.0/lib/overcommit/hook_runner.rb:85:in `consume'

✗ One or more commit-msg hooks failed
```
Commit message to reproduce (without subject):
```


Hello
```

**Comment by sds** [comment]
Thanks for the report, @distorhead!

Fixed in 0527b19.
