### ISSUE TITLE
Avoid printing backtraces for command line?

### ISSUE THREAD

**Issue by proinsias** [brigade/overcommit#528]
I've noticed a difference between how `overcommit` reports errors depending on whether it's run as part of a `git` hook or from the command line.

For example, say I update my `.overcommit.yml` config file, and **don't** run `overcommit --sign`. If I try to commit my changes with `git` using `git commit`, I get a nicely formatted error message that tells me concisely what's wrong and how to fix it:

```bash
Unable to load configuration from '/.../.overcommit.yml': Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
```

However, if I try to run `overcommit --list` or `overcommit --run`, I get a ruby stack trace as part of my error message:

```bash
/Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/configuration_loader.rb:86:in `verify_signatures': Unable to load configuration from '/.../.overcommit.yml': Signature of configuration file has changed! (Overcommit::Exceptions::ConfigurationError)
Run `overcommit --sign` once you've verified the configuration changes.
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/configuration_loader.rb:67:in `load_file'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/configuration_loader.rb:55:in `load_repo_config'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:215:in `config'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:152:in `print_installed_hooks'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:75:in `block in add_information_options'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1395:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1395:in `block in parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1345:in `order!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1437:in `permute!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1459:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:43:in `parse_arguments'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.41.0/bin/overcommit:49:in `<top (required)>'
	from /usr/local/bin/overcommit:22:in `load'
	from /usr/local/bin/overcommit:22:in `<main>'
```

While having that information might be helpful for debugging, I would suggest we hide it from the user during normal operations, as it makes it less clear what the user should do to fix the problem.

**Comment by sds** [comment]
Thanks for the report, @proinsias. 

I believe this was fixed by dd5ec67a9f082460d0a18b03b5f441e59f6292ac (released in 0.42.0).
