### ISSUE TITLE
Support for Go test & Windows can't find path

### ISSUE THREAD

**Issue by pkopac** [brigade/overcommit#534]
I've tried today to add overcommit to our Go repos, but failed. I'm on Windows (with MINGW64 BASH), but also use Linux. Since there's no integrated `go test ./...` I am adding it with a `CustomHook`.

When I try `required_executable: './bin/pre-commit'` `overcommit` cannot find it.
With `verify_signatures: false` it simply fails to find it:
```
$ overcommit --sign
Updating signature for configuration file...

$ overcommit --sign pre-commit
Updated signature of plugin CustomHook

$ overcommit --run
Running pre-commit hooks
Run GoTest...................................................[CustomHook] FAILED
'./pre-commit' is not installed, not in your PATH, or does not have execute permissions
Analyze with go vet...........................................[GoVet] OK

✗ One or more pre-commit hooks failed


$ ls -lth ./bin/pre-commit
-rwxr-xr-x 1 pkopac 197121 41 Jan  5 13:02 ./bin/pre-commit*
```

When I turn verification of signatures on:
```
$ overcommit --run
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_signer.rb:39:in `hook_path': Hook must specify a `required_executable` or `command` that is tracked by git (i.e. is a path relative to the root of the repository) so that it can be signed (Overcommit::Exceptions::InvalidHookDefinition)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_signer.rb:92:in `hook_contents'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_signer.rb:88:in `signature'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_signer.rb:61:in `signature_changed?'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:51:in `select'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:51:in `modified_plugins'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:55:in `check_for_modified_plugins'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:8:in `load_hooks'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:198:in `load_hooks'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:32:in `block in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/hook_runner.rb:28:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:203:in `run_all'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/lib/overcommit/cli.rb:28:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/overcommit-0.41.0/bin/overcommit:49:in `<top (required)>'
        from C:/Ruby24-x64/bin/overcommit:23:in `load'
        from C:/Ruby24-x64/bin/overcommit:23:in `<main>'
```

Working on Linux:
```
Running pre-commit hooks
Run CustomHook...........................................[CustomHook] OK
Analyze with go vet...........................................[GoVet] OK

✓ All pre-commit hooks passed
```

Configuration:
```yaml
PreCommit:
  # https://github.com/brigade/overcommit/pull/530
  # GoLint:
  #   enabled: true
  #   on_warn: fail # Treat all warnings as failures
  GoVet:
    enabled: true
    on_warn: fail
  CustomHook:
    enabled: true
    required_executable: './bin/pre-commit'
```

**Comment by sds** [comment]
Hey @pkopac, thanks for the repot.

None of the active maintainers of Overcommit (that I'm aware of) currently develop on Windows. We'd love to have some help with this issue!

**Comment by pkopac** [comment]
@sds, thanks for your answer. I've since switched fully to Linux, so... feel free to close it.

**Comment by sds** [comment]
Alright, I'm going to close this for now then (but for anyone else reading this, a PR with a fix would be most welcome!)
