### ISSUE TITLE
W3cHtml raises 302 found error

### ISSUE THREAD

**Issue by leemour** [brigade/overcommit#597]
When running W3cHtml if get this error:
```
Hook raised unexpected error
302 "Found"
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http/response.rb:129:in `value'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/w3c_validators-1.3.4/lib/w3c_validators/validator.rb:112:in `send_request'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/w3c_validators-1.3.4/lib/w3c_validators/validator.rb:109:in `send_request'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/w3c_validators-1.3.4/lib/w3c_validators/markup_validator.rb:132:in `validate'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/w3c_validators-1.3.4/lib/w3c_validators/markup_validator.rb:118:in `validate_file'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook/pre_commit/w3c_html.rb:17:in `block in collect_messages'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook/pre_commit/w3c_html.rb:16:in `collect'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook/pre_commit/w3c_html.rb:16:in `collect_messages'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook/pre_commit/w3c_html.rb:7:in `run'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/utils.rb:253:in `with_environment'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook_runner.rb:162:in `run_hook'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook_runner.rb:95:in `block in consume'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook_runner.rb:92:in `loop'
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/overcommit-0.46.0/lib/overcommit/hook_runner.rb:92:in `consume'
```
It is the same issue as https://github.com/w3c-validators/w3c_validators/issues/25 and is caused by deprecated URL used in validator: http://validator.w3.org/check in [default config](https://github.com/brigade/overcommit/blob/master/config/default.yml#L772)

**Comment by leemour** [comment]
I created a PR to fix this https://github.com/brigade/overcommit/pull/598
