### ISSUE TITLE
Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by boardfish** [brigade/overcommit#600]
When installing a Rubocop commit hook, I get the following error:

```
Installing hooks into /home/si/Code/example-repository
Traceback (most recent call last):
        18: from /home/si/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        17: from /home/si/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        16: from /home/si/.rvm/gems/ruby-2.5.1/bin/overcommit:23:in `<main>'
        15: from /home/si/.rvm/gems/ruby-2.5.1/bin/overcommit:23:in `load'
        14: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/bin/overcommit:49:in `<top (required)>'
        13: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/cli.rb:24:in `run'
        12: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/cli.rb:125:in `install_or_uninstall'
        11: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/cli.rb:125:in `each'
        10: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/cli.rb:127:in `block in install_or_uninstall'
         9: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/installer.rb:22:in `run'
         8: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/installer.rb:33:in `install'
         7: from /home/si/.rvm/gems/ruby-2.5.1/gems/overcommit-0.46.0/lib/overcommit/installer.rb:80:in `ensure_directory'
         6: from /home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
         5: from /home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:193:in `each'
         4: from /home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
         3: from /home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
         2: from /home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
         1: from /home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/home/si/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Permission denied @ dir_s_mkdir - /Users (Errno::EACCES)
```

OS: Arch Linux x86_64 
Host: 81H1 Lenovo ideapad 530S-14ARR 
Kernel: 4.18.12-arch1-1-ARCH

I'm pretty sure it's to do with file permissions but I can't trace it back. It's strange that it's looking for a `/Users` directory, if my understanding is correct.

.overcommit.yml in the root of the repository is as follows:

```
PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop'] # Invoke within Bundler context
```
```
└─[$] overcommit -v                                                                [21:08:31]
overcommit 0.46.0
```

**Comment by sds** [comment]
Hey @boardfish, the fact that you're trying to create a directory in `/Users` (according to the line `Permission denied @ dir_s_mkdir - /Users (Errno::EACCES)`) suggests an issue with your local Ruby environment (a bad environment variable that points the runtime at the incorrect directory, perhaps).

I would be able to help you here—there's many potential causes of Ruby looking in the wrong directory. However, if you do find a solution, would love it if you posted it back!
