### ISSUE TITLE
check_for_executable modifies a frozen string

### ISSUE THREAD

**Issue by trcarden** [brigade/overcommit#635]
```ruby 
   # In overcommit-0.47.0/lib/overcommit/hook/base.rb:209
   # frozen_string_literal: true

    # If the hook defines a required executable, check if it's in the path and
    # display the install command if one exists.
    def check_for_executable
      return unless required_executable && !in_path?(required_executable)

      output = "'#{required_executable}' is not installed, not in your PATH, " \
               'or does not have execute permissions'
      output << install_command_prompt

      output
    end
```

As you can clearly see when the first check fails you have a string modification when at the top of the file you have a frozen string literal true.

Here was my back trace 
```
Running pre-commit hooks
Analyze with ESLint..........................................[EsLint] FAILED
Hook raised unexpected error
can't modify frozen String
overcommit-0.47.0/lib/overcommit/hook/base.rb:209:in `check_for_executable'
overcommit-0.47.0/lib/overcommit/hook/base.rb:199:in `check_for_requirements'
overcommit-0.47.0/lib/overcommit/hook/base.rb:44:in `run_and_transform'
overcommit-0.47.0/lib/overcommit/hook_runner.rb:164:in `run_hook'
overcommit-0.47.0/lib/overcommit/hook_runner.rb:97:in `block in consume'
overcommit-0.47.0/lib/overcommit/hook_runner.rb:94:in `loop'
overcommit-0.47.0/lib/overcommit/hook_runner.rb:94:in `consume'

✗ One or more pre-commit hooks failed
```

Running Ruby 2.6, Overcommit 0.47.0

**Comment by sds** [comment]
Thanks for the report!

**Comment by leblangi** [comment]
@sds I saw that you modify the code to fix this issue but now, using the master (I have now the following error:
`'eslint' is not installed, not in your PATH, or does not have execute permissions
Install it by running: npm install -g eslint`

It seems that the "require_executable" no longer use the on in my EsLint configuration in the .overcommit.yml but the default one (default value: eslint)

**Comment by sds** [comment]
Hey @leblangi, please open a new issue with your `.overcommit.yml`, the output you're seeing, and what you expect to see. Thanks.
